services:
  - type: web
    name: badnaam-raja
    runtime: node
    buildCommand: npm install && pip install yt-dlp && DENO_INSTALL=/opt/render/project/.deno sh -c "curl -fsSL https://deno.land/install.sh | sh"
    startCommand: npm start
